name: Build Super Filtered Subscriptions

on:
  workflow_dispatch: # Позволяет запустить вручную кнопкой
  push:
    branches: [main]
    paths:
      - 'scripts/**'
      - 'BlackList'
      - 'WhiteList'
      - 'FavoriteSubBlack'
  schedule:
    - cron: '0 */4 * * *' # Запуск каждые 4 часа

permissions:
  contents: write  # КРИТИЧЕСКИ ВАЖНО для пуша в репо

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Super Filter Script
        run: python scripts/sort_protocols.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output/*.txt
          git add output/*.b64
          # Проверка на наличие изменений, чтобы экшн не падал, если ничего не изменилось
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update FiltredHy2VlessTrojan [$(date +'%d.%m.%Y %H:%M')]"
            git push origin main
          fi
